- name: Play level Variables
  hosts: localhost
  vars:
    course: "Devops"
    tutor: "Siva"
    type: "online"
  tasks:
  - name: To Print the Variables
    vars:
      Course: "JavaFullStack"
    debug:
      msg: "i am chandu priya i am taking {{ Course }}  through {{ type }} tutor is {{ tutor }}. Play Level vars"

  - name: Print Variable    
    ansible.builtin.debug:
      msg: "i am chandu priya i am taking {{ course }}  through {{ type }} tutor is {{ tutor }}. Tasks Level vars"


- name: variables
  hosts: localhost
  vars: #variable declaration
    Course: "Terraform"
    Trainer: "Siva"
    Duration: "15hrs"
  tasks:
  - name: print override information
    vars: # Task level variables
      Course: "DevOps"
    ansible.builtin.debug:
      msg: "Hi, We are learning {{Course}} from Trainer {{Trainer}}, Duration is {{Duration}}."

  - name: print information
    ansible.builtin.debug:
      msg: "Hi, We are learning {{Course}} from Trainer {{Trainer}}, Duration is {{Duration}}."