- name: variables from var file
  hosts: localhost
  vars_files:
  - 05-1vars.yaml
  tasks:
  - name: Print Variable Values From Vars file
    debug:
      msg: "course: {{Course}} Trainer: {{Trainer}} Duration: {{Duration}}"