- name: variables from var file
  hosts: localhosts
  vars_files:
  - vars.yaml
  tasks:
  - name: Print Variable Values From Vars file
    msg: "course: {{Course}} Trainer: {{Traine}} Duration: {{Duration}}"