- name: Display number
  hosts: localhost
  vars_prompt:
  - name: num1
    prompt: enter number
    private: no
  - name: num2
    prompt: enter number
    private: no  
  tasks:  
  - name: Print Greater number
    debug:
      msg: "num1 {{num1}} is greater than num2 {{num2}}"
    when: num1 | int > num2 | int

  - name: Print lesser number
    debug:
      msg: "num1 {{num1}} is less than num2 {{num2}}"
    when: num1 | int < num2 | int 



