- name: loops Demo
  hosts: localhost
  tasks:
  - name: Print loop
    debug:
      msg: " {{item}}"
    loop:
    - sindu
    - siva
    - priya
    - kumar
    - chandu    

- name: install Softwares using loop
  hosts: localhost
  become: yes
  tasks:
  - name: install Softwares
    dnf:
      name: "{{item}}"
      state: latest
    loop:
    - mysql
    - nginx
    - postfix      


- name: install Softwares using loop
  hosts: localhost
  become: yes
  tasks:
  - name: install Softwares
    dnf:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop:
    - {name: 'vim', state: 'latest'}
    - {name: 'wget', state: 'latest'}
    - {name: 'curl', state: 'latest'}      
