- name: loops Demo
  hosts: localhost
  tasks:
  - name: Print loop
    debug:
      msg: " {{item}}"
    loop:
    - sindu
    - siva
    - priya
    - kumar
    - chandu    

- name: install Softwares using loop
  hosts: localhost
  become: yes
  tasks:
  - name: install Softwares
    debug:
      msg: "{{item}}"
      state: latest
    loop:
    - mysql
    - nginx
    - postfix      