# - name: Shell  and command
#   hosts: localhost
#   tasks:
#   - name: list tmp files
#     command: "echo 'Hi, This is from command module' > /tmp/command.txt"

#   - name: List `.log` files in /var/log
#     shell: "ls /var/log | grep '.log' > /tmp/demo.txt" 
  
- name: command vs shell
  hosts: localhost
  tasks:
  - name: command module
    ansible.builtin.command: "echo 'Hi, this is from command module' > /tmp/command.txt "

  - name: shell module
    ansible.builtin.shell: "echo 'Hi, this is from shell module' > /tmp/shell.txt "

    # simple commands without the need of shell variables, envrironment and features like redirections, pipes, & go for command module.
    # If we need to run complex commands or scripts go for shell module.
    # Whatever works in command module, it will work in shell module, but vice versa is not true.
    