- name: Shell  and command
  hosts: localhost
  tasks:
  - name: list tmp files
    command: "echo Hi, This is from command module > /tmp/hi.txt"

  - name: List `.log` files in /var/log
    shell: "ls /var/log | grep '.log' > /tmp/demo.txt" 
  
