- name: Filters different Demos
  hosts: localhost
  vars:
    String: Hello Ansible 
    fruts: ['apple','bunana','apple','pinaple']
    user_details:
      name: sindu
      job: devops
      experience: 3 
  tasks:
  - name: Convert Upper Case
    debug:
      msg: "{{String | upper}}"  

  - name: Convert Lower Case
    debug:
      msg: "{{String | lower}}"

  - name: replace a word
    debug:
      msg: "{{String | replace('Ansible','world')}}" 

  - name: print uniq from list
    debug:
      msg: "{{fruts | unique}}"   

  - name: Sort the List
    debug:
      msg: "{{fruts | sort}}"      

  - name: Before Convert 
    debug:
      msg: "{{user_details}}"

  - name: After convert
    debug:
      msg: "{{user_details | dict2items}}" 

  # If your Ansible version is below 2.8, update the syntax like this:  user_details.keys()   

  - name: Print Keys From dictionary
    debug:
      msg: "{{ user_details.keys() }}"             

  - name: Print Values From dictionary
    debug:
      msg: "{{ user_details.values() }}"    